-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0NuzEoscIimYe/Ze
iXYf+Alip4A+OWzfZMg/fKgeN9OgCgYIKoZIzj0DAQehRANCAASuWlBNacdt1EnP
lbCJn56zRaT9g+iVTYXUucljQc/2+P/WRHSSji14zuG642vncFK7TriSvy1PkPhL
LZDLm51p
-----END PRIVATE KEY-----